language: rust
rust:
 - stable
 - beta
 - nightly
cache: cargo
env:
  global:
    - SAUCE_USERNAME=fantoccini
  matrix:
    - PLATFORM="Windows 10"
    - PLATFORM="Windows 8.1"
    - PLATFORM="macOS 10.13"
    - PLATFORM="macOS 10.12"
addons:
  sauce_connect: true
script:
 - cargo build --verbose
 - cargo test --verbose -- --test-threads=1
matrix:
  allow_failures:
  - rust: nightly
