[package]
name = "fantoccini"
version = "0.14.2"
edition = "2018"

description = "High-level API for programmatically interacting with web pages through WebDriver."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/fantoccini"
homepage = "https://github.com/jonhoo/fantoccini"
repository = "https://github.com/jonhoo/fantoccini.git"

keywords = ["webdriver", "chromedriver", "geckodriver", "phantomjs", "automation"]
categories = ["api-bindings", "development-tools::testing", "web-programming::http-client"]

license = "MIT/Apache-2.0"

[features]
default = ["rustls-tls"]
rustls-tls = ["hyper-rustls"]
openssl-tls = ["hyper-tls"]

[dependencies]
webdriver = "0.41.0"
url = "2.0.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
futures-core = "0.3.0"
futures-util = "0.3.0"
tokio = { version = "0.2.4", features = [ "sync" ] }
hyper = { version = "0.13.0", features = [ "stream" ] }
cookie = { version = "0.14", features = ["percent-encode"] }
base64 = "0.12"
hyper-rustls = { version = "0.21.0", optional = true }
hyper-tls = { version = "0.4.0", optional = true }
mime = "0.3.9"
http = "0.2"

[dev-dependencies]
tokio = { version = "0.2.0", features = [ "full" ] }
serial_test = "0.5"
serial_test_derive = "0.5"
warp = "0.2.2"
