[package]
name = "fantoccini"
version = "0.16.0"
edition = "2018"

description = "High-level API for programmatically interacting with web pages through WebDriver."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/fantoccini"
homepage = "https://github.com/jonhoo/fantoccini"
repository = "https://github.com/jonhoo/fantoccini.git"

keywords = ["webdriver", "chromedriver", "geckodriver", "phantomjs", "automation"]
categories = ["api-bindings", "development-tools::testing", "web-programming::http-client"]

license = "MIT/Apache-2.0"

[dependencies]
webdriver = { version = "0.43.0", default-features = false }
url = "2.0.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
futures-core = "0.3.0"
futures-util = "0.3.0"
tokio = { version = "1", features = [ "sync", "rt" ] }
hyper = { version = "0.14", features = [ "stream", "client", "http1" ] }
hyper-tls = "0.5.0"
cookie = { version = "0.14", features = ["percent-encode"] }
base64 = "0.13"
mime = "0.3.9"
http = "0.2"

[dev-dependencies]
tokio = { version = "1", features = [ "full" ] }
hyper = { version = "0.14", features = [ "server" ] }
serial_test = "0.5"
serial_test_derive = "0.5"
