[package]
name = "fantoccini"
version = "0.11.8"
edition = "2018"

description = "High-level API for programmatically interacting with web pages through WebDriver."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/fantoccini"
homepage = "https://github.com/jonhoo/fantoccini"
repository = "https://github.com/jonhoo/fantoccini.git"

keywords = ["webdriver", "chromedriver", "geckodriver", "phantomjs", "automation"]
categories = ["api-bindings", "development-tools::testing", "web-programming::http-client"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/fantoccini" }
maintenance = { status = "looking-for-maintainer" }

[dependencies]
webdriver = "0.38.0"
url = "1.5.0"
serde = "1.0"
serde_json = "1.0"
futures-core-preview = { version = "0.3.0-alpha.17" }
futures-util-preview = { version = "0.3.0-alpha.17" }
futures-channel-preview = { version = "0.3.0-alpha.17" }
tokio = { git = "https://github.com/tokio-rs/tokio.git" }
hyper = { git = "https://github.com/hyperium/hyper.git" }
hyper-tls = { git = "https://github.com/95th/hyper-tls.git" }
cookie = { version = "0.11", features = ["percent-encode"] }
base64 = "0.9.1"
mime = "0.3.9"
http = "0.1"
